"""posts table

Revision ID: f79f3bd5c686
Revises: 53382fb7d264
Create Date: 2021-12-15 14:24:02.514399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f79f3bd5c686"
down_revision = "53382fb7d264"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "post",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("body", sa.String(length=140), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_post_timestamp"), "post", ["timestamp"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_post_timestamp"), table_name="post")
    op.drop_table("post")
    # ### end Alembic commands ###
